Btc 130 refs vs query selector
beyond-the-cloud-dev/posts pull request #20
Opened 2023-11-22 19:15 UTC by pgajek2

2023-11-23 08:56 UTC, niou-ns reviewed
tylko ten jeden link bym dodał, poza tym mi się bardzo podoba, zajebisty, fajny i szybki artykuł. znakomita robota.

2023-11-23 08:56 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
>  - `querySelectorAll()` returns a static (not live) NodeList representing a list of the document's elements that match the specified group of selectors.
dodałbym linka:

[NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)

2023-11-23 12:48 UTC, osieckiAdam commented
nie wrzucałeś go jeszcze na wordpressa czy jestem ślepy?

2023-11-23 13:04 UTC, osieckiAdam reviewed
dobry artykuł, nie mam większych uwag, tylko trochę przemyśleń w tekście, niekoniecznie do uwzględniania w ostatecznej wersji artykułu

2023-11-23 13:04 UTC, osieckiAdam commented on refs-vs-query-selector-in-lwc/README.md
> +> If the component runs in an org with Lightning Locker enabled, be aware of a potential memory leak. If possible, the org should enable Lightning Web Security. **Alternatively, consider using refs i
Cały ten akapit widziałbym jako odrobinę jaśniejszy i klarowny:
Generalnie sprawa się ma tak, że refy powinny być używane zawsze i wszędzie. Dla normalnego programisty wystarczy wrzucić info o Big O notation (O1) i wszystko jasne, ale pamiętajmy że masa developerów SF to nie programiści z krwi i kości
Tej informacji brakuje mi wprost, podkreślenia że ze względu na istotne różnice w performance refy powinny być używane zawsze gdzie się da. Oczywiście napisałeś to, ale mam wrażenie że ten argument gdzieś ginie w tych wszystkich informacjach, bo zaraz jest ta informacja (moim zdaniem trochę niejasna) o LWS. zwłaszcza że refs wymagają włączonego LWC (a przynajmniej tak było w spring 23 podczas releasu i nie sądzę żeby to się od tego czasu zmieniło)
Więc moim zdaniem to jest do sprawdzenia i zamiast cytowania tego fragmentu dokumentacji (który w mojej ocenie jest błędny) możesz po prostu napisać że ze względu na potencjalne memory leaki salesforce zaleca używanie LWC i refów
czyli widzę to tak że chciałbym jasno zobaczyć: okej używaj zawsze refów, chyba że wpadasz pod jeden z poniższych use casów

2023-11-23 13:04 UTC, osieckiAdam commented on refs-vs-query-selector-in-lwc/README.md
> +> If the component runs in an org with Lightning Locker enabled, be aware of a potential memory leak. If possible, the org should enable Lightning Web Security. **Alternatively, consider using refs i
ale w sumie jak to przeczytałem drugi raz na spokojnie to właściwie tak to u ciebie wygląda, więc chyba do sprawdzenia tylko ta kwestia LWS a refy. Na moment releasu na pewno tak było - refy mi się nie kompilowały bo my nadal w Eonie nie mamy Lightning Web security.

a no i dobrze by było podlinkować bezpośrednio tutaj tą dokumentację na którą siępowołujesz

2023-11-23 13:04 UTC, osieckiAdam commented on refs-vs-query-selector-in-lwc/README.md
> +- **refs is read-only** - `this.refs` is read-only object
to jest ważny punkt, można go rozwinąć tam na dole, bo to w sumie jest dosyć powszechny use case, że sobie ziomeczki querują element i dynamicznie modyfikują css albo coś innego, warto to mocniej podkreślić

2023-11-24 07:26 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
> +> If the component runs in an org with Lightning Locker enabled, be aware of a potential memory leak. If possible, the org should enable Lightning Web Security. **Alternatively, consider using refs i
też nie mamy włączonego LWS i się kompilują ;)

2023-11-24 07:34 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
> +> If the component runs in an org with Lightning Locker enabled, be aware of a potential memory leak. If possible, the org should enable Lightning Web Security. **Alternatively, consider using refs i
@pgajek2 mam jeszcze jedną propozycję - oprócz O1 i ON jak by Ci się chciało zrobić testy i wrzucić wyniki byłoby zajebiście:
`
console.time();
   for (let i = 0; i < 100000; i++) {
      this.refs.selector;
   }
console.timeEnd();

console.time();
   for (let i = 0; i < 100000; i++) {
      this.template.querySelector([ten-sam-element]);
   }
console.timeEnd();
`

2023-11-24 07:35 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
> +- **refs is read-only** - `this.refs` is read-only object
pytanie od publiczności: czy this.refs można używać w connectedCallback czy trzeba zaczekać na renderedCallback?

2023-11-25 15:37 UTC, pgajek2 commented
> nie wrzucałeś go jeszcze na wordpressa czy jestem ślepy?

Jeszcze nie, najpierw review :D

2023-11-25 16:07 UTC, pgajek2 commented on refs-vs-query-selector-in-lwc/README.md
> +- **refs is read-only** - `this.refs` is read-only object
Sprawdziłem, nie można w connectedCallbacku :(

2023-11-25 18:01 UTC, janeksledziewski requested changes
A da się tak?

```
this.refs.myDiv.querySelectorAll('costam')
```

Wydaje się, że może być przydatne do np. for:each

2023-11-25 18:12 UTC, pgajek2 commented on refs-vs-query-selector-in-lwc/README.md
> +There are a few problems with accessibility:
Good point!

2023-11-25 18:12 UTC, pgajek2 commented
> A da się tak?
> 
> ```
> this.refs.myDiv.querySelectorAll('costam')
> ```
> 
> Wydaje się, że może być przydatne do np. for:each

To jest dobre! dodam!

2023-11-27 07:54 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
> +> Use renderedCallback() to understand the state of the "inside" world (a component's UI and property state), and use connectedCallback() to understand the state of the "outside" world (a component's
to zdanie mi się w chuj podoba.

2023-11-27 07:55 UTC, niou-ns requested changes

2023-11-27 07:55 UTC, niou-ns commented on refs-vs-query-selector-in-lwc/README.md
> +> Use renderedCallback() to understand the state of the "inside" world (a component's UI and property state), and use connectedCallback() to understand the state of the "outside" world (a component's
ale dodałbym coś :D

(a components containing environment in the moment of components creation).

2023-11-30 19:38 UTC, niou-ns approved these changes

2024-01-15 09:33 UTC, merged