How to check if list is empty in apex
beyond-the-cloud-dev/posts pull request #8
Opened 2022-10-08 21:29 UTC by osieckiAdam

2022-10-10 07:22 UTC, pgajek2 requested changes

2022-10-14 08:25 UTC, osieckiAdam reviewed
wszystkie uwagi uwzględnione, plus przesiałem to z gramarly

2022-10-14 08:25 UTC, osieckiAdam commented on how-to-check-if-list-is-empty-in-apex/README.md
> +```
ogarnięte, dla podbicia dramaturgii użyłem trzech ikonek zamiast jednej

2022-11-06 21:00 UTC, janeksledziewski commented on how-to-check-if-list-is-empty-in-apex/README.md
> +The reason is that most native list functions (including size() and isEmpty()) do not check if the variable is null internally, so working with null lists may cause NullPointerException:
All native functions?

2023-10-15 18:21 UTC, merged