new system assert class - draft
beyond-the-cloud-dev/posts pull request #9
Opened 2022-11-06 11:39 UTC by osieckiAdam

[WIP]
merytorycznie jest już całość, @pgajek2 @janeksledziewski prośba o weryfikację pod tym kątem

TODO: jakiś spell checking, grammarly i tym podobne

2022-11-06 11:40 UTC, osieckiAdam commented
może jakiś clickbaitowy tytuł się przydał, @pgajek2 any idea?

2022-11-06 20:07 UTC, pgajek2 requested changes

2022-11-06 20:07 UTC, pgajek2 commented on new-system-assert-class/README.md
> +System class also contains a lot of different methods like ```scheduleBatch()```, ```debug()```, ```now()```. They obviously have nothing in common with assertions. It looks like the System class is
Czytałem gdzieś (choć nie wiem czy to prawda), że psychologicznie bardziej wiarygodne są zdania. 
Zaczynające się w nowej lini.
A nie zdania pisane jednym ciągiem. 

No i czytelniej jest :D

2022-11-06 20:07 UTC, pgajek2 commented on new-system-assert-class/README.md
> +## New methods are just syntactic sugar
h3 tutaj `###`, bo wymieniasz to jako część `Less is better`

2022-11-06 20:07 UTC, pgajek2 commented on new-system-assert-class/README.md
> +
A może tutaj jakiś mapping? że ta stara == tej nowej.

2022-11-06 20:16 UTC, osieckiAdam commented on new-system-assert-class/README.md
> +## New methods are just syntactic sugar
A to specjalnie tak zrobiłem bo to jest kolejny punkt, chciałem zrobić taką płynność między akapitami

2022-11-06 20:16 UTC, osieckiAdam commented on new-system-assert-class/README.md
> +System class also contains a lot of different methods like ```scheduleBatch()```, ```debug()```, ```now()```. They obviously have nothing in common with assertions. It looks like the System class is
Ok ale to znaczy ze wszystkie zdania od nowej linijki?

2022-11-06 20:18 UTC, osieckiAdam commented on new-system-assert-class/README.md
> +
Hmmm wtedy trzeba by było skopiować tą tabelę z punktu 6 i zrobić trochę powtórzenie tych samych informacji
W ogóle to usunąłem numerację z akapitów, muszę tu podmienić punkt 6 na dokładna nazwę sekcji

2022-11-06 20:19 UTC, osieckiAdam commented on new-system-assert-class/README.md
> +
Bo w tej tabelce, nie wiem czy zwróciłeś uwagę dokładnie taki mapping jest, każda nowa metoda ma stary odpowiednik

2022-11-06 20:37 UTC, pgajek2 commented on new-system-assert-class/README.md
> +## New methods are just syntactic sugar
Okss

2022-11-06 20:37 UTC, pgajek2 commented on new-system-assert-class/README.md
> +System class also contains a lot of different methods like ```scheduleBatch()```, ```debug()```, ```now()```. They obviously have nothing in common with assertions. It looks like the System class is
hmm. chyba tylko te, które chcesz aby ładnie wybrzmiały.

2022-11-06 20:37 UTC, pgajek2 commented on new-system-assert-class/README.md
> +
Oks, fair enough!

2022-11-06 20:58 UTC, janeksledziewski reviewed
Chyba "flow" lepiej byłby zachowany jakby argumenty za były oddzielone od tych przeciw. W tym momencie nie byłem pewnie jakie twoje będzie zdanie. + Można to porównać do innych industry standard jak np. JUnit. Czyli, czy SF idzie w kierunku bardziej otwartego środowiska.

2022-11-06 20:58 UTC, janeksledziewski commented on new-system-assert-class/README.md
> +Salesforce in release notes recommends that developers start using the new System.Assert as soon as possible and what is more to replace existing assertions. Let's see what are the arguments for doin
"The first reason why I like the new Assert class is:". To zdanie wydaje się nie potrzebne, bo powody wymieniasz w kolejnych nagłówkach.

2022-11-06 20:58 UTC, janeksledziewski commented on new-system-assert-class/README.md
>  Assert.isNull('null');
.areEqual, już chyba nie zwraca ładniej wiadomości bez "msg"? :)

2022-11-07 18:05 UTC, osieckiAdam commented on new-system-assert-class/README.md
> +Salesforce in release notes recommends that developers start using the new System.Assert as soon as possible and what is more to replace existing assertions. Let's see what are the arguments for doin
ok, usunąłem, nie ma co na siłę trzaskać większej ilości znaków

2022-11-07 20:26 UTC, merged